sudo: false
os:
    - linux
# dbus 1.2.6 fails to build on macos. And we have no key storage there anyway.
#    - osx
cache:
    directories:
        - $HOME/.stack
addons:
  apt:
    sources:
        - hvr-ghc
    packages:
        - libgmp-dev
        - libsodium-dev

before_install:
    - |
        if [ "$TRAVIS_OS_NAME" == "linux" ]; then
          mkdir -p ~/.local/bin
          export PATH=$HOME/.local/bin:$PATH
          travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
          export PATH=/opt/ghc/8.0.2/bin:$PATH
        fi
    - |
        if [ "$TRAVIS_OS_NAME" == "osx" ]; then
          brew update
          brew install haskell-stack
        fi

install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then stack --no-terminal setup ; fi
    - stack --no-terminal --install-ghc test --only-dependencies

script:
    - stack --no-terminal test
