sudo: false
os:
    - linux
    - osx
cache:
    directories:
        - $HOME/.stack
addons:
  apt:
    sources:
        - hvr-ghc
    packages:
        - libgmp-dev
        - ghc-8.0.2
env:
    - BUILD=stack STACK_ARGS="--system-ghc"

before_install:
    - |
        set -ex
        if [ "$TRAVIS_OS_NAME" == "linux" ]; then
          mkdir -p ~/.local/bin
          export PATH=$HOME/.local/bin:$PATH
          travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
          export PATH=/opt/ghc/8.0.2/bin:$PATH
        fi
        set +ex
    - |
        if [ "$TRAVIS_OS_NAME" == "osx" ]; then
          brew update
          brew install haskell-stack
        fi

install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then stack $STACK_ARGS --no-terminal setup ; fi
    - |
        set -ex
        stack $STACK_ARGS --no-terminal test --only-snapshot
        set +ex

script:
    - |
        set -ex
        stack $STACK_ARGS --no-terminal test private-cloud
        set +ex
